version: "1"

# More info at https://hub.docker.com/r/teddysun/xray and https://github.com/cheehoong/asustor-apk-xray
services:
  xray:
    container_name: xray
    image: teddysun/xray:latest
    network_mode: bridge
    ports:
      - "9000:9000/tcp"
#      - "9000:9000/udp"
    environment:
      TZ: 'Asia/Singapore'
# Volumes store your data between container upgrades
    volumes:
      - '/share/Docker/xray-docker/:/etc/xray/'
    restart: unless-stopped
